version: "3"

services:
  php8:
    build:
      context: ./docker/php8
    container_name: ${COMPOSE_PROJECT_NAME}-app
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html/
      - ./docker/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php8/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8
  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}-db
    ports:
      - "3306:3306"
    depends_on:
      - php8
    environment:
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      SERVICE_NAME: mysql
  mysql_phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: "root"
      UPLOAD_LIMIT: 2048M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 3000